import type { Metadata } from "next";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "MyWeb",
  description: "Generated by Simplenotion",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
                  <div className=" w-full bg-blue-400 p-10 text-center">Header</div>
        <div className=" min-h-full flex flex-col">
        {children}

        </div>
                  <div className=" w-full bg-blue-400 p-10 text-center">Footer</div>
      </body>
    </html>
  );
}
